[package]
name = "luna"
version = "0.1.0"
authors = ["Severen Redwood <severen@shrike.me>"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/severen/luna.git"

edition = "2021"

[dependencies]
anyhow = "1.0.65"
thiserror = "1.0.35"
clap = { version = "3.2.22", features = ["derive", "unicode", "wrap_help"] }
rustyline = "10.0.0"
directories-next = "2.0.0"
logos = "0.12.1"

[dependencies.derive_more]
version = "0.99.17"
default_features = false
features = ["display"]
